# .github/FUNDING.yml

# Substitua [SEU-USUARIO-GITHUB] pelo seu nick real do GitHub (ex: devmp)
github: [MatheusPereiraSilva]

# Aqui está o seu LivePix configurado
custom: ["https://livepix.gg/devmp"]